package packet

// Opcode mirrors RealmServerOpCode — Asda2 range only (1000+).
// WoW opcodes (0-999) are intentionally omitted.
type Opcode uint16

const (
	// ---- Auth / Login ----
	Ping                              Opcode = 1000
	AuthorizeRequest                  Opcode = 1003
	AuthorizeResponse                 Opcode = 1004
	SelectChanelRequest               Opcode = 1005
	CharacterNames                    Opcode = 1006
	CharacterInfos                    Opcode = 1007
	SelectServerRequest               Opcode = 1012
	ChanelInfoResponse                Opcode = 1013
	CreateCharacterRequest            Opcode = 1014
	CreateCharacterResponseOne        Opcode = 1015
	EnterGameRequset                  Opcode = 1016
	EnterGameRespose                  Opcode = 1017
	EnterWorldIpeResponse             Opcode = 1021
	ShowCharactersView                Opcode = 1025
	CreateCharacterResponse           Opcode = 1026
	EnterGameResponseItemsOnCharacter Opcode = 1027
	LocationInit                      Opcode = 20000

	// ---- World / Character ----
	CharacterInitOnLogin        Opcode = 4001
	CharacterInfoSessIdPosition Opcode = 4003
	CharacterVisibleNow         Opcode = 4005
	CharacterDelete             Opcode = 4011
	CharacterAddEquipment       Opcode = 4021
	CharacterRemoveEquipment    Opcode = 4023
	Emote                       Opcode = 4024
	EmoteResponse               Opcode = 4025
	LvlUp                       Opcode = 4036
	ExpGained                   Opcode = 4038
	ShopInventoryInfo           Opcode = 4045
	SomeInitGS                  Opcode = 4046
	RegularInventoryInfo        Opcode = 4048
	SomeInitGSOne               Opcode = 4049
	ShowWarehouse               Opcode = 4050
	ShowWarehouseItems          Opcode = 4051
	ShowWarehouseEnd            Opcode = 4052
	SelfDeath                   Opcode = 4053
	ResurectOnDeathPlace        Opcode = 4054
	ResurectWithChangeLocation  Opcode = 4055
	Resurect                    Opcode = 4056
	CharHpUpdate                Opcode = 4058
	CharMpUpdate                Opcode = 4059
	UpdateStats                 Opcode = 4060
	UpdateStatsOne              Opcode = 4064
	NpcVisiableNow              Opcode = 4067
	SettingsFlags               Opcode = 4070
	Disconnect                  Opcode = 4101
	MonstrTakesDamageSecondary  Opcode = 4102
	GuildInfoOnLogin            Opcode = 4104
	ClanFlagAndClanNameInfoSelf Opcode = 4105
	GuildMembersInfo            Opcode = 4107
	GuildMembersInfoEnded       Opcode = 4108
	CharacterInitOnChanelChange Opcode = 5058
	FastItemSlotsInfo           Opcode = 5059
	SetFastItemSlot             Opcode = 5067

	// ---- Movement ----
	StartMove          Opcode = 4006
	StartMoveCommon    Opcode = 4007
	EndMove            Opcode = 4008
	EndMoveCommon      Opcode = 4009
	MonstVisible       Opcode = 4013
	MonstMove          Opcode = 4015
	MonstrStateChanged Opcode = 4017

	// ---- Combat ----
	StartAtack                  Opcode = 4026
	StartAtackResponse          Opcode = 4027
	ContinueAtack               Opcode = 4028
	MonstrTakeDmg               Opcode = 4029
	StartAtackCharacter         Opcode = 4201
	StartAtackCharacterResponse Opcode = 4202
	AtackCharacter              Opcode = 4203
	AtackCharacterRes           Opcode = 4204
	SetAtackStateGui            Opcode = 4205
	FightingModeChanged         Opcode = 4206

	// ---- PvP ----
	PvpRquest                  Opcode = 4302
	AnswerPvpRequestOrStartPvp Opcode = 4303
	DuelEnded                  Opcode = 4304
	PvpRoundEffect             Opcode = 4305

	// ---- Items / Inventory ----
	ReplaceItem              Opcode = 5000
	ItemReplaced             Opcode = 5001
	ItemDroped               Opcode = 5005
	RemoveItem               Opcode = 5006
	ItemRemovedFromInventory Opcode = 5007
	PushToWarehouse          Opcode = 5008
	ItemsPushedToWarehouse   Opcode = 5009
	TakeItemFromWarehouse    Opcode = 5010
	ItemFormWarehouseTaked   Opcode = 5011
	PickUpItem               Opcode = 5012
	ItemPickuped             Opcode = 5013
	RemoveItemFromWorld      Opcode = 5015
	SellItem                 Opcode = 5018
	SellItemResponse         Opcode = 5019
	BuyItem                  Opcode = 5020
	BuyItemResponse          Opcode = 5021
	MoveSoulStoneOut         Opcode = 5022
	SowelRemoved             Opcode = 5023
	MoveSoulStoneIn          Opcode = 5024
	ItemSoweled              Opcode = 5025
	UseItem                  Opcode = 5028
	CharUsedItem             Opcode = 5029
	UpdateAmmoResponse       Opcode = 5030
	ChangeProfession         Opcode = 5042
	ClientUiActionRequest    Opcode = 5045
	QuestsList               Opcode = 5047
	TeleportedByCristal      Opcode = 5055
	ClientLoadVerification   Opcode = 5056
	ShowAvatarWhItems        Opcode = 4210
	AvatarWhItemsList        Opcode = 4211
	AvatarWhItemsListEnded   Opcode = 4212

	// ---- Skills / Spells ----
	SkillsInfo              Opcode = 5251
	LearnSkill              Opcode = 5253
	SkillLearned            Opcode = 5254
	UseSkill                Opcode = 5256
	UseSkillResult          Opcode = 5257
	AnimateSkillStrike      Opcode = 5270
	SetSkillCooldown        Opcode = 5271
	CharacterBuffed         Opcode = 5272
	BuffEnded               Opcode = 5273
	SkillReady              Opcode = 5274
	CancelSkill             Opcode = 6142
	UseSoulGuardSkill       Opcode = 6158
	AllSkillsReseted        Opcode = 6057
	AllSkillsResetedInfoMsg Opcode = 5462
	SkillReseted            Opcode = 5464
	SkillLearnedFirstTime   Opcode = 6056

	// ---- Chat ----
	NormalChat               Opcode = 5084
	NormalChatResponse       Opcode = 5085
	AnnChat                  Opcode = 5086
	AnnouncementChatResponse Opcode = 5087
	AnnChatResponse          Opcode = 5087
	WishperChatRequest       Opcode = 5088
	WishperChat              Opcode = 5089
	GlobalChat               Opcode = 6561
	GlobalMessage            Opcode = 6615

	// ---- Party ----
	SendPartyInvite                               Opcode = 5090
	InviteToPartyResponseOrRequestToAnotherPlayer Opcode = 5091
	PartyInvireAnswer                             Opcode = 5092
	PartyIniteResponse                            Opcode = 5093
	InviteSecodCharToParty                        Opcode = 5094
	LeaveFromParty                                Opcode = 5098
	ExileFromParty                                Opcode = 5100
	PartyMemberKicked                             Opcode = 5101
	PartyHasBroken                                Opcode = 5103
	PartyMemberPositionInfo                       Opcode = 5104
	PartyChat                                     Opcode = 5105
	PartyChatResponse                             Opcode = 5106
	PartyInfo                                     Opcode = 5107
	PartyMemberBuffInfo                           Opcode = 5108
	PartyMemberInitialInfo                        Opcode = 5109

	// ---- Soulmate ----
	SoulmateEnterdGame      Opcode = 5110
	SoulMateHpMpUpdate      Opcode = 5111
	SoulmateBuffUpdateInfo  Opcode = 5112
	SoulmateRequest         Opcode = 5200
	SoulmateRequestResponse Opcode = 5201
	AnswerSoulmateRequest   Opcode = 5202
	YouHaveSoulmatedWith    Opcode = 5203
	DisbandSoulMate         Opcode = 5204
	DisbandSoulMateResult   Opcode = 5207
	SoulMateInfoInit        Opcode = 5220
	SoulmatePosition        Opcode = 5223
	SoulmateLoggedOut       Opcode = 5226
	UseSoulmateSkill        Opcode = 5231
	SoulmateSkillCast       Opcode = 5233
	SoulmateSkillUsed       Opcode = 5234
	SoulmateSummoningYou    Opcode = 5236
	FindSoulMateReq         Opcode = 5483
	SoulmatesList           Opcode = 5484
	SoulmatesListEnded      Opcode = 5485

	// ---- Trade ----
	TradeRequest           Opcode = 5282
	TradeRequestResponse   Opcode = 5283
	StartTradeResponse     Opcode = 5284
	TradeStarted           Opcode = 5285
	CancelTrade            Opcode = 5286
	TradeRejected          Opcode = 5287
	PushItemToTrade        Opcode = 5288
	ItemToTradePushed      Opcode = 5289
	PopItemFromTrade       Opcode = 5290
	ConfimTradeOne         Opcode = 5291
	ConfimTradeFromOponent Opcode = 5292
	ConfimTradeTwo         Opcode = 5293
	ShopTradeComplete      Opcode = 5294
	RegularTradeComplete   Opcode = 5295

	// ---- Guild ----
	CreateGuild                      Opcode = 4109
	GuildCreated                     Opcode = 4110
	DisolveGuild                     Opcode = 4111
	GuildDisolved                    Opcode = 4112
	SendInviteGuild                  Opcode = 4113
	SendInviteGuiledResponse         Opcode = 4114
	JoinMyGuildRequest               Opcode = 4115
	JoinGuildResponse                Opcode = 4116
	LeaveGuild                       Opcode = 4117
	YouHaveLeftGuild                 Opcode = 4118
	KickFromGuild                    Opcode = 4119
	YouHaveBeenKickedFromGuild       Opcode = 4120
	UpdateGuildInfo                  Opcode = 4121
	GuildNotification                Opcode = 4122
	GuildChatReq                     Opcode = 4123
	GuildChatRes                     Opcode = 4124
	SetPrivilegies                   Opcode = 4125
	PrivilagiesChanged               Opcode = 4126
	ChangeClanMemberRank             Opcode = 4127
	ChangeClanMemberRankAccessResult Opcode = 4128
	RegisterGuildCrest               Opcode = 4129
	RegisterGuildCrestResult         Opcode = 4130
	EditClanNotice                   Opcode = 4131
	AnnouncementEdited               Opcode = 4132
	AskForGuildHistory               Opcode = 4139
	GuildHistory                     Opcode = 4140
	GuildHistoryEnded                Opcode = 4141
	ReqUpdateGuildPoints             Opcode = 4142
	UpdateGuildPoints                Opcode = 4143
	DonateGuildPoints                Opcode = 4144
	GuildPointsDonated               Opcode = 4145
	LevelUpGuild                     Opcode = 4146
	GuildLeveluped                   Opcode = 4147
	GuildSkillsInfo                  Opcode = 4148
	GuildSkillStatusChanged          Opcode = 4149
	LearnClanSkill                   Opcode = 4161
	ClanSkillLearned                 Opcode = 4162
	ActivateGuildSkill               Opcode = 4163
	GuildSkillActivated              Opcode = 4164
	ImpeachmentReuest                Opcode = 4167
	ImpeachmentStatus                Opcode = 4168
	ImpeachmentAnswer                Opcode = 4169
	ImpeachmentVote                  Opcode = 4170
	ImpeachmentResult                Opcode = 4171

	// ---- Friends ----
	AddFriend                Opcode = 4150
	FriendAdded              Opcode = 4151
	InviteFromeSomeoneFriend Opcode = 4152
	InviteFriendAnswer       Opcode = 4153
	DeleteFromFriendList     Opcode = 4154
	DeletedFromFriendList    Opcode = 4155
	ShowFriendList           Opcode = 4156
	FriendList               Opcode = 4157
	FriendListEnded          Opcode = 4158
	UpdateFriendShipPoints   Opcode = 6047

	// ---- Fishing ----
	StartFishing             Opcode = 6167
	FishingStarted           Opcode = 6168
	EndFishing               Opcode = 6171
	FishingEnded             Opcode = 6172
	SomeOneStartedFishing    Opcode = 6173
	FishingBooksInfo         Opcode = 6174
	FishingBookListEnded     Opcode = 6175
	RegisterFishingBook      Opcode = 6176
	FishingBookRegistered    Opcode = 6177
	ReciveFishingBookReward  Opcode = 6182
	FishingBookRewardRecived Opcode = 6183
	UpdateFishingLvl         Opcode = 6164

	// ---- Battleground / War ----
	RegisterToWar                     Opcode = 6706
	RegisteredToWar                   Opcode = 6707
	CancleWarPatipication             Opcode = 6708
	WarPartipicationCanceled          Opcode = 6709
	YouCanEnterWarAfter               Opcode = 6710
	YouCanEnterWar                    Opcode = 6711
	FactionAndHonorPointsInit         Opcode = 6713
	EnterBatlefield                   Opcode = 6714
	WarTeamList                       Opcode = 6715
	WarTeamListEnded                  Opcode = 6716
	ShowWarUnit                       Opcode = 6717
	WarChatRequest                    Opcode = 6718
	WarChatResponse                   Opcode = 6719
	CharacterPositionInfoOnWar        Opcode = 6720
	CharacterHasLeftWar               Opcode = 6721
	CharacterFactionAndFactionRank    Opcode = 6722
	StartOcupyPoint                   Opcode = 6723
	OccupyingPointStarted             Opcode = 6724
	UpdatePointInfo                   Opcode = 6725
	WarPointsPreInit                  Opcode = 6726
	WarCurrentActionInfo              Opcode = 6728
	TeamPoints                        Opcode = 6729
	SomeOneKilledSomeOne              Opcode = 6730
	LeaveBattleGround                 Opcode = 6731
	WarEnded                          Opcode = 6732
	WarEndedOne                       Opcode = 6733
	WarRemainingTime                  Opcode = 6736
	WarHasBeenCanceled                Opcode = 6740
	HowManyPeopleInWarTeams           Opcode = 6742
	RequestUpdateWarScreenManagerData Opcode = 6700
	UpdateWarManagerScreenData        Opcode = 6701
	SelectFactionReq                  Opcode = 6702
	SelectFactionRes                  Opcode = 6703
	DismissPlayerFromWar              Opcode = 6186
	QuestionDismissPlayerOrNot        Opcode = 6188
	AnswerDismissPlayer               Opcode = 6189
	DissmissResult                    Opcode = 6190
	WiningFactionInfo                 Opcode = 6257

	// ---- Pets ----
	SummonPet                 Opcode = 6100
	PetSummonOrUnSummond      Opcode = 6101
	HatchEgg                  Opcode = 6102
	EggHatched                Opcode = 6103
	UpdatePetHunger           Opcode = 6104
	UpdatePetExp              Opcode = 6105
	InitPetInfoOnLogin        Opcode = 6106
	PetGoesSleepDueStarvation Opcode = 6107
	ResurectPet               Opcode = 6108
	PetResurected             Opcode = 6109
	RemovePet                 Opcode = 6110
	PetRemoved                Opcode = 6111
	PetSyntes                 Opcode = 6112
	PetSyntesResult           Opcode = 6113
	ChangePetName             Opcode = 6118
	PetNameChanged            Opcode = 6119
	CharacterInfoPet          Opcode = 6120
	ExpandPetBox              Opcode = 6121
	PetBoxExpanded            Opcode = 6122
	PetBoxSizeInit            Opcode = 6123
	BreakPetLvlLimit          Opcode = 6148
	PetLevelLimitBreaked      Opcode = 6149

	// ---- Mounts ----
	MountBoxSizeInit              Opcode = 6761
	OwnedMountsList               Opcode = 6762
	SummonMount                   Opcode = 6763
	CHaracterOnMountStatusChanged Opcode = 6764
	MountSummoning                Opcode = 6765
	GetOnMount                    Opcode = 6766
	VeicheStatusChanged           Opcode = 6767
	RegisterVeiche                Opcode = 6768
	VeicheRegistered              Opcode = 6769

	// ---- Private Shop ----
	OpenPrivateShopWindow                  Opcode = 6300
	PrivateShopWindoOpened                 Opcode = 6301
	OpenPrivateShop                        Opcode = 6302
	PrivateShopOpened                      Opcode = 6303
	TradeStatusTextWindow                  Opcode = 6304
	CloseCharacterTradeShop                Opcode = 6305
	CloseCharacterTradeShopResponseToOwner Opcode = 6306
	ViewCharacterTradeShop                 Opcode = 6307
	CharacterPrivateShopInfo               Opcode = 6308
	BuyItemFromCharacterPrivateShop        Opcode = 6309
	ItemBuyedFromPrivateShop               Opcode = 6310
	ItemBuyedFromPrivateShopToOwnerNotify  Opcode = 6311
	PrivateShopChatNotificationAboutBuy    Opcode = 6312
	PrivateShopChatReq                     Opcode = 6313
	PrivateShopChatRes                     Opcode = 6314
	PrivateShopChatNotification            Opcode = 6315

	// ---- Mail ----
	OpenMailBox        Opcode = 6618
	MailsList          Opcode = 6619
	SendMailMessage    Opcode = 6620
	MailMessageSended  Opcode = 6621
	ShowMailMsg        Opcode = 6622
	MailMessageInfo    Opcode = 6623
	TakeMailItem       Opcode = 6624
	MailItemTaked      Opcode = 6625
	DeleteMailMessage  Opcode = 6626
	MailMessageDeleted Opcode = 6627
	YouHaveNewMail     Opcode = 6628
	CloseMailBox       Opcode = 5466
	MailBoxClosed      Opcode = 5467

	// ---- Titles ----
	YouGetNewTitle   Opcode = 6065
	GetedTitles      Opcode = 6066
	SetTitle         Opcode = 6067
	ChangeChannel    Opcode = 6084
	TitleDiscovered  Opcode = 6085
	DiscoveredTitles Opcode = 6086

	// ---- Crafting / Enchanting ----
	LeanedRecipes            Opcode = 6597
	LearnRecipe              Opcode = 6598
	RecipeLeadned            Opcode = 6599
	Craft                    Opcode = 6602
	Crafted                  Opcode = 6603
	AdvacedEnchantWeapon     Opcode = 6500
	AdvancedEnchantDone      Opcode = 6501
	DisasembleEquipment      Opcode = 6502
	EquipmentDisasembled     Opcode = 6503
	UpgradeItemRequest       Opcode = 6504
	UpgradeItemResponse      Opcode = 6505
	UpgradeResetRequest      Opcode = 6506
	UpgradeResetResponse     Opcode = 6507
	CombineItem              Opcode = 6098
	DisassembleAvatar        Opcode = 6629
	AvatarDissasembled       Opcode = 6630
	StartAvatarSynthesis     Opcode = 6631
	AvatarSynthesisResult    Opcode = 6632
	SoketAvatar              Opcode = 6635
	AvatarSocketed           Opcode = 6636
	ExchangeOption           Opcode = 6553
	ExchangeItemOptionResult Opcode = 6554

	// ---- Teleport ----
	TeleportByCristal    Opcode = 5477
	UseTeleportScroll    Opcode = 5458
	TeleportScrollUsed   Opcode = 5459
	SaveBindLocation     Opcode = 5280
	SaveLocation         Opcode = 6220
	LocationSaved        Opcode = 6221
	DeleteSavedLocation  Opcode = 6222
	SavedLocationDeleted Opcode = 6223
	SavedLocationsInit   Opcode = 6225

	// ---- Digging ----
	StartDig         Opcode = 5428
	StartDigResponse Opcode = 5429
	DigEnded         Opcode = 5431

	// ---- Style ----
	ChangeFaceOrHair  Opcode = 5470
	FaceOrHairChanged Opcode = 5471

	// ---- Shop Items (premium) ----
	UseShopItem            Opcode = 5450
	UpdateShopItemInfo     Opcode = 5451
	ShopItemUsed           Opcode = 5453
	CancelFunctionalItem   Opcode = 5454
	StopUseFunctionalItem  Opcode = 5455
	WarehouseSlotsExpanded Opcode = 5456
	ByuItemFromWarshop     Opcode = 6162
	ItemFromWarshopBuyed   Opcode = 6163
	LongTimeBuffsInfo      Opcode = 6633
	PremiumLongBuffInfo    Opcode = 6634
	OpenBooster            Opcode = 5468
	BosterOpened           Opcode = 5469
	OpenPackage            Opcode = 6096
	OpenPackageResponse    Opcode = 6097

	// ---- Misc ----
	ClientCanLoginToGS                  Opcode = 6004
	SomeNewItemRecived                  Opcode = 6226
	SelectCharacter                     Opcode = 6538
	SelectCharacterRespone              Opcode = 6539
	GetCharecterInfo                    Opcode = 5478
	CharacterFullInfo                   Opcode = 5479
	WhoIsHere                           Opcode = 5480
	WhoIsHereList                       Opcode = 5481
	WhoIsHereListEnded                  Opcode = 5482
	SpeedChanged                        Opcode = 6071
	U6072                               Opcode = 6072
	NpcBuffed                           Opcode = 6079
	AppleExpGained                      Opcode = 6049
	EatApple                            Opcode = 6575
	AppleRandom                         Opcode = 6576
	GetApplePrize                       Opcode = 6579
	AppleEatResult                      Opcode = 6580
	WingsInfo                           Opcode = 6585
	SummonBoss                          Opcode = 6124
	MonsterSummoned                     Opcode = 6125
	DisplayItem                         Opcode = 6129
	ItemDisplayed                       Opcode = 6130
	TransformToPet                      Opcode = 6637
	SetClientTime                       Opcode = 6759
	CharacterRegularEquipmentInfo       Opcode = 7006
	ClientIdleTick                      Opcode = 9915
	U8215                               Opcode = 8215
	U8226                               Opcode = 8226
	ClientPreLocationVerification       Opcode = 33215
	ChangeNameRequest                   Opcode = 6138
	ChangeNameResponse                  Opcode = 6139
	IHaveLearnedTutorial                Opcode = 6184
	PreResurect                         Opcode = 5306
	UpdateDurability                    Opcode = 6570
	RepairItem                          Opcode = 6571
	RepairItemResponse                  Opcode = 6572
	GlobalChatWithItem                  Opcode = 6560
	GlobalChatRemoveItem                Opcode = 6610
	BuffsOnCharacterInfo                Opcode = 6154
	CharacterFriendShip                 Opcode = 6152
	CharacterInfoClanName               Opcode = 6153
	ShowSoulGuardResponse               Opcode = 6156
	SetSkiillPowersStats                Opcode = 6157
	DissmissPlayerFromChatRoom          Opcode = 6250
	DissmisedFromCharRoomResult         Opcode = 6251
	CreateChatRoom                      Opcode = 6240
	ChatRoomCreated                     Opcode = 6241
	EnterChatRoom                       Opcode = 6242
	EnterChatRoomResult                 Opcode = 6243
	CloseChatRoom                       Opcode = 6244
	ChatRoomClosed                      Opcode = 6245
	SendRoomChatMessage                 Opcode = 6246
	RoomChatMsg                         Opcode = 6247
	ChatRoomVisible                     Opcode = 6248
	ChatRoomEvent                       Opcode = 6249
	StoreAvatarItems                    Opcode = 6258
	AvatarItemsStored                   Opcode = 6259
	RetriveItemsFromAvatarWh            Opcode = 6260
	ItemsFromAvatarWhRetrived           Opcode = 6221
	GlobalChatWithItemResponse          Opcode = 6561
	SendSoulmateMessage                 Opcode = 6052
	SoulmatemessageSended               Opcode = 6053
	IncomingSoulmateMessage             Opcode = 6055
	CharacterSoulMateIntrodactionUpdate Opcode = 6080
	TeleportToSoulmateAnswer            Opcode = 5427
	UseChangeFactionItem                Opcode = 6704
	FactionReseted                      Opcode = 6705
	SoulmateSkillUsed2                  Opcode = 5234
	SetSkillCooldown2                   Opcode = 5271
	IDontKnowAboutCHaracter             Opcode = 5416
	CharacterPlaceInTitleRating         Opcode = 6068
)
