-- Asda2 Go current database additions.
-- Keep this file Asda2-only. Do not import unused WoW/WCell tables here.

CREATE TABLE IF NOT EXISTS Asda2BaseStat (
	ClassID TINYINT UNSIGNED NOT NULL,
	Level TINYINT UNSIGNED NOT NULL,
	BaseHealth INT NOT NULL DEFAULT 0,
	BasePower INT NOT NULL DEFAULT 0,
	Attr1 INT NOT NULL DEFAULT 0,
	Attr2 INT NOT NULL DEFAULT 0,
	Attr3 INT NOT NULL DEFAULT 0,
	Attr4 INT NOT NULL DEFAULT 0,
	Attr5 INT NOT NULL DEFAULT 0,
	Attr6 INT NOT NULL DEFAULT 0,
	Source VARCHAR(80) NOT NULL DEFAULT 'BaseStats',
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ClassID, Level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2ItemTemplate (
	ItemId INT NOT NULL,
	Name VARCHAR(120) NOT NULL DEFAULT '',
	Kind TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Category SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	Quality TINYINT UNSIGNED NOT NULL DEFAULT 0,
	AuctionLevelCriterion TINYINT UNSIGNED NOT NULL DEFAULT 0,
	InventoryType TINYINT UNSIGNED NOT NULL DEFAULT 2,
	EquipmentSlot SMALLINT NOT NULL DEFAULT -1,
	RequiredLevel TINYINT UNSIGNED NOT NULL DEFAULT 0,
	RequiredProfession TINYINT UNSIGNED NOT NULL DEFAULT 0,
	MaxDurability TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Weight SMALLINT UNSIGNED NOT NULL DEFAULT 1,
	BuyPrice INT NOT NULL DEFAULT 0,
	SellPrice INT NOT NULL DEFAULT 0,
	MaxStack INT NOT NULL DEFAULT 1,
	IsStackable TINYINT(1) NOT NULL DEFAULT 0,
	SowelSockets TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ValueOnUse INT NOT NULL DEFAULT 0,
	AttackTime INT NOT NULL DEFAULT 0,
	AttackRange SMALLINT NOT NULL DEFAULT 0,
	SowelBonusType INT NOT NULL DEFAULT 0,
	SowelBonusValue INT NOT NULL DEFAULT 0,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ItemId),
	KEY IX_Asda2ItemTemplate_Kind (Kind, IsEnabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2CraftRecipe (
	RecipeId SMALLINT NOT NULL,
	Name VARCHAR(120) NOT NULL DEFAULT '',
	ResultItemId INT NOT NULL,
	ResultAmount INT NOT NULL DEFAULT 1,
	RequiredCraftingLevel TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Material1ItemId INT NOT NULL DEFAULT 0,
	Material1Amount INT NOT NULL DEFAULT 0,
	Material2ItemId INT NOT NULL DEFAULT 0,
	Material2Amount INT NOT NULL DEFAULT 0,
	Material3ItemId INT NOT NULL DEFAULT 0,
	Material3Amount INT NOT NULL DEFAULT 0,
	Material4ItemId INT NOT NULL DEFAULT 0,
	Material4Amount INT NOT NULL DEFAULT 0,
	Material5ItemId INT NOT NULL DEFAULT 0,
	Material5Amount INT NOT NULL DEFAULT 0,
	Material6ItemId INT NOT NULL DEFAULT 0,
	Material6Amount INT NOT NULL DEFAULT 0,
	Result2ItemId INT NOT NULL DEFAULT 0,
	Result2Amount INT NOT NULL DEFAULT 0,
	Result3ItemId INT NOT NULL DEFAULT 0,
	Result3Amount INT NOT NULL DEFAULT 0,
	Result4ItemId INT NOT NULL DEFAULT 0,
	Result4Amount INT NOT NULL DEFAULT 0,
	Result5ItemId INT NOT NULL DEFAULT 0,
	Result5Amount INT NOT NULL DEFAULT 0,
	Result6ItemId INT NOT NULL DEFAULT 0,
	Result6Amount INT NOT NULL DEFAULT 0,
	Result7ItemId INT NOT NULL DEFAULT 0,
	Result7Amount INT NOT NULL DEFAULT 0,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (RecipeId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2CharacterSkill (
	OwnerId INT UNSIGNED NOT NULL,
	SkillId SMALLINT NOT NULL,
	Level TINYINT UNSIGNED NOT NULL DEFAULT 1,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (OwnerId, SkillId),
	KEY IX_Asda2CharacterSkill_Owner (OwnerId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2SkillTemplate (
	RealId SMALLINT NOT NULL,
	Level TINYINT UNSIGNED NOT NULL DEFAULT 1,
	LearnLevel TINYINT UNSIGNED NOT NULL DEFAULT 0,
	RequiredProfessionLevel TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ClassGroup TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ClassMask SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	Cost BIGINT NOT NULL DEFAULT 0,
	PowerCost SMALLINT NOT NULL DEFAULT 0,
	CooldownMillis INT NOT NULL DEFAULT 0,
	MaxRange TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Damage INT NOT NULL DEFAULT 0,
	EffectId INT NOT NULL DEFAULT 271,
	Effect0Misc SMALLINT NOT NULL DEFAULT 0,
	Effect0Type SMALLINT NOT NULL DEFAULT 0,
	Effect0BasePoints INT NOT NULL DEFAULT 0,
	Effect1Type SMALLINT NOT NULL DEFAULT 0,
	Effect1BasePoints INT NOT NULL DEFAULT 0,
	TargetFlags INT UNSIGNED NOT NULL DEFAULT 0,
	RequiredTargetType TINYINT UNSIGNED NOT NULL DEFAULT 0,
	SoulGuardLevel TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CastTimeMillis INT NOT NULL DEFAULT 0,
	DurationMillis INT NOT NULL DEFAULT 0,
	IsPassive TINYINT(1) NOT NULL DEFAULT 0,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (RealId, Level),
	KEY IX_Asda2SkillTemplate_Class (ClassGroup, ClassMask, IsEnabled),
	KEY IX_Asda2SkillTemplate_SoulGuard (SoulGuardLevel, IsEnabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2TeleportingPointRecord (
	Guid BIGINT NOT NULL,
	OwnerId INT UNSIGNED NOT NULL,
	Slot TINYINT UNSIGNED NOT NULL,
	Name VARCHAR(32) NOT NULL DEFAULT '',
	MapId SMALLINT UNSIGNED NOT NULL,
	X SMALLINT NOT NULL,
	Y SMALLINT NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (Guid),
	UNIQUE KEY UX_Asda2TeleportingPointRecord_OwnerSlot (OwnerId, Slot),
	KEY IX_Asda2TeleportingPointRecord_Owner (OwnerId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2Friendship (
	OwnerId INT UNSIGNED NOT NULL,
	FriendId INT UNSIGNED NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (OwnerId, FriendId),
	KEY IX_Asda2Friendship_Friend (FriendId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2Guild (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Name VARCHAR(17) NOT NULL,
	Level TINYINT UNSIGNED NOT NULL DEFAULT 1,
	MaxMembers TINYINT UNSIGNED NOT NULL DEFAULT 30,
	Points INT NOT NULL DEFAULT 0,
	WaveLimit TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Crest VARBINARY(40) NOT NULL DEFAULT '',
	MOTD VARCHAR(293) NOT NULL DEFAULT 'Default MOTD',
	NoticeWriter VARCHAR(20) NOT NULL DEFAULT '',
	NoticeTime DATETIME NOT NULL DEFAULT '1970-01-01 00:00:01',
	LeaderCharacterId INT UNSIGNED NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT '1970-01-01 00:00:01',
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	UNIQUE KEY UX_Asda2Guild_Name (Name),
	KEY IX_Asda2Guild_Leader (LeaderCharacterId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2GuildRank (
	GuildId INT UNSIGNED NOT NULL,
	RankIndex TINYINT UNSIGNED NOT NULL,
	Name VARCHAR(20) NOT NULL DEFAULT '',
	Privileges SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (GuildId, RankIndex),
	CONSTRAINT FK_Asda2GuildRank_Guild
		FOREIGN KEY (GuildId) REFERENCES Asda2Guild (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2GuildMember (
	CharacterId INT UNSIGNED NOT NULL,
	GuildId INT UNSIGNED NOT NULL,
	AccountId INT UNSIGNED NOT NULL,
	CharNum TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Name VARCHAR(20) NOT NULL DEFAULT '',
	Level TINYINT UNSIGNED NOT NULL DEFAULT 1,
	ProfessionLevel TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Class TINYINT UNSIGNED NOT NULL DEFAULT 0,
	RankIndex TINYINT UNSIGNED NOT NULL DEFAULT 4,
	PublicNote VARCHAR(60) NOT NULL DEFAULT '',
	LastLogin DATETIME NOT NULL DEFAULT '1970-01-01 00:00:01',
	LastMapId SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT '1970-01-01 00:00:01',
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (CharacterId),
	KEY IX_Asda2GuildMember_Guild (GuildId, RankIndex, Name),
	KEY IX_Asda2GuildMember_Account (AccountId),
	CONSTRAINT FK_Asda2GuildMember_Guild
		FOREIGN KEY (GuildId) REFERENCES Asda2Guild (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2GuildSkill (
	GuildId INT UNSIGNED NOT NULL,
	SkillId SMALLINT NOT NULL,
	Level TINYINT UNSIGNED NOT NULL DEFAULT 1,
	IsActivated TINYINT(1) NOT NULL DEFAULT 0,
	LastMaintenance DATETIME NOT NULL DEFAULT '1970-01-01 00:00:01',
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (GuildId, SkillId),
	CONSTRAINT FK_Asda2GuildSkill_Guild
		FOREIGN KEY (GuildId) REFERENCES Asda2Guild (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2GuildHistory (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	GuildId INT UNSIGNED NOT NULL,
	Type TINYINT UNSIGNED NOT NULL,
	Value INT NOT NULL DEFAULT 0,
	TriggerName VARCHAR(20) NOT NULL DEFAULT '',
	EventTime VARCHAR(17) NOT NULL DEFAULT '',
	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	KEY IX_Asda2GuildHistory_Guild (GuildId, ID),
	CONSTRAINT FK_Asda2GuildHistory_Guild
		FOREIGN KEY (GuildId) REFERENCES Asda2Guild (ID)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2Portal (
	Id INT UNSIGNED NOT NULL,
	FromX SMALLINT NOT NULL,
	FromY SMALLINT NOT NULL,
	FromMap SMALLINT UNSIGNED NOT NULL,
	ToX SMALLINT NOT NULL,
	ToY SMALLINT NOT NULL,
	ToMap SMALLINT UNSIGNED NOT NULL,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (Id),
	KEY IX_Asda2Portal_FromMap (FromMap, IsEnabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2Weather (
	MapId SMALLINT UNSIGNED NOT NULL,
	Channel SMALLINT NOT NULL DEFAULT -1,
	WeatherType TINYINT UNSIGNED NOT NULL DEFAULT 0,
	Level TINYINT UNSIGNED NOT NULL DEFAULT 0,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (MapId, Channel),
	KEY IX_Asda2Weather_Channel (Channel, IsEnabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2MonsterTemplate (
	EntryId SMALLINT UNSIGNED NOT NULL,
	Name VARCHAR(80) NOT NULL,
	Level TINYINT UNSIGNED NOT NULL DEFAULT 1,
	MaxHealth INT NOT NULL DEFAULT 100,
	MoveMs SMALLINT NOT NULL DEFAULT 150,
	WalkSpeed DOUBLE NOT NULL DEFAULT 1,
	RunSpeed DOUBLE NOT NULL DEFAULT 3.5,
	MinDamage DOUBLE NOT NULL DEFAULT 5,
	MaxDamage DOUBLE NOT NULL DEFAULT 5,
	BaseAttackMs INT NOT NULL DEFAULT 2000,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (EntryId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2MonsterSpawn (
	SpawnId INT UNSIGNED NOT NULL,
	EntryId SMALLINT UNSIGNED NOT NULL,
	MapId SMALLINT UNSIGNED NOT NULL,
	LocalX SMALLINT NOT NULL,
	LocalY SMALLINT NOT NULL,
	RespawnSeconds INT NOT NULL DEFAULT 30,
	Channel SMALLINT NOT NULL DEFAULT -1,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (SpawnId),
	KEY IX_Asda2MonsterSpawn_Map (MapId, IsEnabled),
	KEY IX_Asda2MonsterSpawn_Channel (Channel, IsEnabled),
	CONSTRAINT FK_Asda2MonsterSpawn_Template
		FOREIGN KEY (EntryId) REFERENCES Asda2MonsterTemplate (EntryId)
		ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2NpcTemplate (
	EntryId SMALLINT UNSIGNED NOT NULL,
	Name VARCHAR(80) NOT NULL,
	Kind TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ClassGroup TINYINT UNSIGNED NOT NULL DEFAULT 0,
	IsTrainer TINYINT(1) NOT NULL DEFAULT 0,
	InteractionKind TINYINT UNSIGNED NOT NULL DEFAULT 0,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (EntryId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2NpcSpawn (
	SpawnId INT UNSIGNED NOT NULL,
	EntryId SMALLINT UNSIGNED NOT NULL,
	MapId SMALLINT UNSIGNED NOT NULL,
	LocalX SMALLINT NOT NULL,
	LocalY SMALLINT NOT NULL,
	Channel SMALLINT NOT NULL DEFAULT -1,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (SpawnId),
	KEY IX_Asda2NpcSpawn_Map (MapId, IsEnabled),
	KEY IX_Asda2NpcSpawn_Channel (Channel, IsEnabled),
	CONSTRAINT FK_Asda2NpcSpawn_Template
		FOREIGN KEY (EntryId) REFERENCES Asda2NpcTemplate (EntryId)
		ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Asda2NpcVendorItem (
	VendorEntryId SMALLINT UNSIGNED NOT NULL,
	ItemId INT NOT NULL,
	SortOrder SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	IsEnabled TINYINT(1) NOT NULL DEFAULT 1,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (VendorEntryId, ItemId),
	KEY IX_Asda2NpcVendorItem_Item (ItemId, IsEnabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

